# PoseFormerV2

In [2]:
import numpy as np

### Code to make one combined npz file out of all the npz files for the individual frames



In [1]:
#create a folder named "combined" in the pose3D_keypoints folder
import numpy as np
import os

# List of directories containing the .npz files
directories = [
    r'C:\Users\localtest\Desktop\MA\PoseFormerV2\demo\output\02_squat_5_hoch\pose3D_keypoints',
   
]

for directory in directories:
    # Output directory for the combined file
    output_directory = os.path.join(directory, 'combined')
    os.makedirs(output_directory, exist_ok=True)  # Ensure the output directory exists

    # Retrieve all npz files sorted by name (assuming they are sequentially named)
    files = sorted([f for f in os.listdir(directory) if f.endswith('.npz')])

    # Dictionary to hold all keypoints from all frames
    all_keypoints = {}

    # Load each .npz file and retrieve its content
    for filename in files:
        frame_index = filename.split('_')[0]  # Assuming filename format 'XXXX_3D_keypoints.npz'
        file_path = os.path.join(directory, filename)
        data = np.load(file_path)
        all_keypoints[f'frame_{frame_index}'] = data['keypoints_3d']

    # Save all keypoints in a single .npz file
    output_path = os.path.join(output_directory, 'combined_keypoints.npz')
    np.savez(output_path, **all_keypoints)
    print(f"All keypoints combined into: {output_path}")


All keypoints combined into: C:\Users\localtest\Desktop\MA\PoseFormerV2\demo\output\02_squat_5_hoch\pose3D_keypoints\combined\combined_keypoints.npz


In [8]:
data = np.load(r'E:\Datenerhebung MA\PoseFormerV2 Daten\AEN262\Cam1\17_tubes_1\pose3D_keypoints\combined\combined_keypoints.npz')


In [9]:
print("Arrays in the NPZ file:", data.files)

Arrays in the NPZ file: []


In [7]:
specific_array = data['frame_0005']
print("specific_array:", specific_array)
specific_array2 = data['frame_0100']
print("specific_array2:", specific_array2)

specific_array: [[ 0.          0.          0.15064745]
 [ 0.11051494  0.05473553  0.14203462]
 [-0.00406489  0.48324507  0.22314505]
 [ 0.12623438  0.24491972  0.0195439 ]
 [-0.1105116  -0.05473369  0.15925722]
 [-0.32854715  0.2726097   0.26078779]
 [-0.13877401  0.06093442  0.        ]
 [-0.05111395  0.116116    0.3354149 ]
 [-0.18721569  0.26213586  0.5077594 ]
 [-0.23501563  0.33032942  0.5401264 ]
 [-0.23914492  0.2728693   0.6138778 ]
 [-0.29650867  0.16916078  0.4745111 ]
 [-0.4537642   0.06522785  0.3015593 ]
 [-0.45543814  0.31267488  0.25516403]
 [-0.06129982  0.32335094  0.4725662 ]
 [-0.15835103  0.4889629   0.24719267]
 [-0.35726917  0.51159704  0.11796306]]
specific_array2: [[ 0.          0.          0.6771157 ]
 [ 0.12276611  0.02369345  0.6806498 ]
 [ 0.11718816  0.27276772  0.353351  ]
 [ 0.2296194   0.25927782  0.00213969]
 [-0.12276375 -0.02369159  0.67358327]
 [-0.14243075  0.16402505  0.3172377 ]
 [ 0.00747965  0.1539132   0.        ]
 [-0.01678364  0.03469676  0.8

convert to csv

In [2]:
import numpy as np
import csv
import os

# Funktion zur Verarbeitung einer einzelnen .npz-Datei
def process_npz_file(input_file_path):
    # Lade die .npz-Datei
    data = np.load(input_file_path)

    # Erstelle den Pfad zur Ausgabedatei (gleicher Ordner wie die Eingabedatei)
    output_file_path = os.path.splitext(input_file_path)[0] + ".csv"

    # Öffne eine CSV-Datei zum Schreiben des Outputs
    with open(output_file_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)

        # Initialisiere einen Zähler für die Zeilen-Nummerierung
        row_number = 1

        # Schleife über jeden Frame in der .npz-Datei
        for frame_name in data.files:
            # Rufe das Array für den aktuellen Frame ab
            frame_array = data[frame_name]

            # Flache das mehrdimensionale Array zu einem 1D-Array ab
            flattened_array = frame_array.flatten()

            # Entferne die Spalten 23 bis 34 (Indizes 22 bis 33)
            filtered_array = np.delete(flattened_array, np.s_[21:33])

            # Füge die Zeilen-Nummerierung an den Anfang des Arrays hinzu
            numbered_array = np.insert(filtered_array, 0, row_number)

            # Schreibe das nummerierte Array als Zeile in die CSV-Datei
            writer.writerow(numbered_array)

            # Inkrementiere die Zeilen-Nummerierung
            row_number += 1

    print(f"Konvertierung abgeschlossen: {output_file_path}")

# Mehrere Ordner mit .npz-Dateien angeben
input_folders = [
    r'C:\Users\localtest\Desktop\MA\PoseFormerV2\demo\output\02_squat_5_hoch\pose3D_keypoints\combined',
]

# Alle Ordner durchgehen
for input_folder in input_folders:
    if not os.path.isdir(input_folder):
        print(f"Ordner nicht gefunden: {input_folder}")
        continue

    # Alle Dateien im Ordner durchgehen
    for file_name in os.listdir(input_folder):
        # Überprüfen, ob es sich um eine .npz-Datei handelt
        if file_name.endswith(".npz"):
            input_file_path = os.path.join(input_folder, file_name)
            process_npz_file(input_file_path)


Konvertierung abgeschlossen: C:\Users\localtest\Desktop\MA\PoseFormerV2\demo\output\02_squat_5_hoch\pose3D_keypoints\combined\combined_keypoints.csv


# MediaPipe

In [ ]:
import os
import pandas as pd

# Listen von Eingabe- und Ausgabeordnern
input_directories = [
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity0',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity1',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity2',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity0',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity1',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity2',
   
]

output_directories = [
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity0\formatted',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity1\formatted',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam5_hoch\Complexity2\formatted',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity0\formatted',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity1\formatted',
    r'E:\Datenerhebung MA\MediaPipe\NSN261\Cam6_hoch\Complexity2\formatted',

]

# Specify the landmarks to include in the desired order
selected_landmarks = [24, 26, 28, 23, 25, 27, 11, 13, 15, 12, 14, 16]

# Funktion zum Bearbeiten von Dateien in mehreren Ordnern
for input_directory, output_directory in zip(input_directories, output_directories):
    # Alle Dateien im Eingabeordner durchgehen
    for file_name in os.listdir(input_directory):
        # Nur CSV-Dateien verarbeiten
        if file_name.endswith(".csv"):
            input_file_path = os.path.join(input_directory, file_name)

            # Datei einlesen
            data = pd.read_csv(input_file_path)

            # Get unique frame numbers
            frames = data['frame'].unique()

            # Initialize a dictionary to store the data in the desired format
            data_dict = {'Frame': []}

            # Create columns for each selected landmark (X, Y, Z)
            for landmark in selected_landmarks:
                data_dict[f'Landmark_{landmark}_X'] = []
                data_dict[f'Landmark_{landmark}_Y'] = []
                data_dict[f'Landmark_{landmark}_Z'] = []

            # Loop through each frame
            for frame in frames:
                # Filter data for the current frame
                frame_data = data[data['frame'] == frame]

                # Add the frame number to the dictionary
                data_dict['Frame'].append(frame)

                # Add X, Y, Z coordinates for each selected landmark
                for landmark in selected_landmarks:
                    landmark_data = frame_data[frame_data['landmark_index'] == landmark]
                    if not landmark_data.empty:
                        data_dict[f'Landmark_{landmark}_X'].append(landmark_data['x'].values[0])
                        data_dict[f'Landmark_{landmark}_Y'].append(landmark_data['y'].values[0])
                        data_dict[f'Landmark_{landmark}_Z'].append(landmark_data['z'].values[0])
                    else:
                        # If landmark data is missing, append NaN
                        data_dict[f'Landmark_{landmark}_X'].append(float('nan'))
                        data_dict[f'Landmark_{landmark}_Y'].append(float('nan'))
                        data_dict[f'Landmark_{landmark}_Z'].append(float('nan'))

            # Create a DataFrame from the dictionary
            formatted_data = pd.DataFrame(data_dict)

            # Der Dateiname mit _formatted anpassen
            base_name, ext = os.path.splitext(file_name)
            output_file_name = f"{base_name}_formatted{ext}"

            # Ausgabe-Dateipfad erstellen
            output_file_path = os.path.join(output_directory, output_file_name)

            # Save the formatted data to a new CSV file without headers
            formatted_data.to_csv(output_file_path, index=False, header=False)
            print(f"Formatted data saved to {output_file_path}")
